### ISSUE TITLE
Usage with HystrixFeign

### ISSUE THREAD

**Issue by shawakash54** [mwiede/metrics-feign#7]
Hey, I recently saw this project, looks really good !

I was not able to follow on how to make it work with HystrixFeign ?

**Comment by mwiede** [comment]
Some time has passed since I worked on this library. It seems feign itself introduced a better way of adding metrics now, have a look at their readme and their code at https://github.com/OpenFeign/feign/blob/master/dropwizard-metrics5/src/main/java/feign/metrics5/Metrics5Capability.java

**Comment by shawakash54** [comment]
Yes, but the metrics5capability is not providing metrics around 1xx, 2xx, 3xx, 4xx, and 5xx responses. At least, I was not able to find them. Can you please confirm if I am wrong ?

**Comment by mwiede** [comment]
Yes you are right, the metrics from metrics5capability contain different metrics.

I took your request as motivation to adopt my decorator classes towards the new API.

I tried with Hystrix like this

```
HystrixFeign.builder().
...
                .addCapability(new AnnotionMetricsCapability(metricRegistry))
```

Please have a try.
